# Generated by Django 2.2 on 2023-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='top_rated',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
