# Generated by Django 2.2 on 2023-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230708_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='diametr',
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
