# Generated by Django 2.2 on 2023-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230708_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='diametr',
        ),
        migrations.AddField(
            model_name='item',
            name='diameter',
            field=models.FloatField(null=True),
        ),
    ]
