# Generated by Django 2.2 on 2023-07-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230713_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='articul',
        ),
    ]
