# Generated by Django 2.2 on 2023-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='brand',
            field=models.ManyToManyField(default=None, to='core.Brand'),
        ),
    ]
