# Generated by Django 2.2 on 2023-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230716_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='max_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='min_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
