# Generated by Django 2.2 on 2023-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230805_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
