# Generated by Django 2.2 on 2023-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230814_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Parket',
        ),
    ]
