# Generated by Django 2.2 on 2023-08-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230815_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='design',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='faska',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selection',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='wood_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
