# Generated by Django 2.2 on 2023-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230815_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decor_obrabotka',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
